version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - media-files:/vol/web/media:ro
      - ./nginx-media.conf:/etc/nginx/vhost.d/kicat.co.kr:ro
      - ./nginx-media.conf:/etc/nginx/vhost.d/www.kicat.co.kr:ro
      - ./nginx-media.conf:/etc/nginx/vhost.d/kicat.graceed.co.uk:ro
    restart: unless-stopped
    networks:
      - proxy-network

  # Optional: Let's Encrypt companion for automatic SSL
  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - acme-state:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=question106@gmail.com
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    networks:
      - proxy-network

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  acme-state:
  media-files:
    external: true
    name: kicat-production_media-files

networks:
  proxy-network:
    name: proxy-network
    driver: bridge 