version: '3.8'

services:
  # Django Application
  app:
    build:
      context: https://github.com/question106/kicat-django0601.git 
      dockerfile: Dockerfile
    container_name: kicat-app
    volumes:
      - static-files:/vol/web/static
      - media-files:/vol/web/media
    environment:
      # Domain configuration for nginx-proxy
      - VIRTUAL_HOST=kicat.co.kr,www.kicat.co.kr,kicat.graceed.co.uk
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=kicat.co.kr,www.kicat.co.kr,kicat.graceed.co.uk
      - LETSENCRYPT_EMAIL=question106@gmail.com
      
      # Django production settings
      - DEBUG=0
      - SECRET_KEY=your-production-secret-key-here
      - ALLOWED_HOSTS=kicat.co.kr www.kicat.co.kr kicat.graceed.co.uk
      
      # Database configuration
      - DB_HOST=db
      - DB_NAME=kicat_production
      - DB_USER=postgres
      - DB_PASSWORD=your-secure-database-password
      
      # Additional settings
      - DJANGO_SETTINGS_MODULE=app.settings
      
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - proxy-network
      - kicat-internal

  # Nginx configuration setup (runs once then exits)
  nginx-config:
    image: alpine:latest
    container_name: kicat-nginx-config
    volumes:
      - nginx-vhost:/etc/nginx/vhost.d
      - media-files:/vol/web/media:ro
    command: |
      sh -c "
        echo 'Setting up nginx media configuration for kicat domains...'
        
        # Create media serving config for each domain
        cat > /etc/nginx/vhost.d/kicat.co.kr << 'EOF'
      location /media/ {
          alias /vol/web/media/;
          expires 1y;
          add_header Cache-Control 'public, immutable';
          access_log off;
      }
      EOF
        
        cat > /etc/nginx/vhost.d/www.kicat.co.kr << 'EOF'  
      location /media/ {
          alias /vol/web/media/;
          expires 1y;
          add_header Cache-Control 'public, immutable';
          access_log off;
      }
      EOF
        
        cat > /etc/nginx/vhost.d/kicat.graceed.co.uk << 'EOF'
      location /media/ {
          alias /vol/web/media/;
          expires 1y;
          add_header Cache-Control 'public, immutable';
          access_log off;
      }
      EOF
        
        echo '✅ nginx media configuration created for kicat domains'
      "
    restart: "no"
    networks:
      - proxy-network

  # PostgreSQL Database
  db:
    image: postgres:13-alpine
    container_name: kicat-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kicat_production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your-secure-database-password
    restart: unless-stopped
    networks:
      - kicat-internal

volumes:
  static-files:
  media-files:
  postgres-data:
  nginx-vhost:
    external: true
    name: nginx-proxy_nginx-vhost

networks:
  proxy-network:
    external: true
  kicat-internal:
    driver: bridge 