version: '3.8'

services:
  # Your Django App
  app:
    build: .
    container_name: site1-app
    volumes:
      - static-files:/vol/web/static
      - media-files:/vol/web/media
    environment:
      # Domain configuration for nginx-proxy
      - VIRTUAL_HOST=${SITE_DOMAIN},www.${SITE_DOMAIN}
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=${SITE_DOMAIN},www.${SITE_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      
      # Django settings
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${SITE_DOMAIN},www.${SITE_DOMAIN}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - proxy-network
      - site1-internal

  # Database for this site
  db:
    image: postgres:13-alpine
    container_name: site1-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: unless-stopped
    networks:
      - site1-internal

volumes:
  static-files:
  media-files:
  postgres-data:

networks:
  proxy-network:
    external: true
  site1-internal:
    driver: bridge 