# Generated by Django 4.2.21 on 2025-06-04 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='수상명 또는 학술대회명을 입력하세요', max_length=200, verbose_name='수상/행사명')),
                ('description', models.TextField(help_text='수상 내용 또는 행사에 대한 자세한 설명을 입력하세요', verbose_name='상세 설명')),
                ('date', models.DateField(help_text='수상일 또는 행사 개최일을 입력하세요', verbose_name='수상/개최일')),
                ('location', models.CharField(help_text='수상 장소 또는 행사 개최지를 입력하세요', max_length=200, verbose_name='장소')),
                ('image', models.ImageField(help_text='수상 또는 행사와 관련된 이미지를 업로드하세요', upload_to='awards/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='대표 이미지')),
                ('short_description', models.CharField(blank=True, help_text='카드에 표시될 간략한 설명 (예: 2022년 한국번역가협회)', max_length=100, verbose_name='간략 설명')),
                ('is_active', models.BooleanField(default=True, help_text='체크 해제 시 웹사이트에서 숨겨집니다', verbose_name='활성화')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='낮은 숫자가 먼저 표시됩니다', verbose_name='표시 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '수상 및 학술대회',
                'verbose_name_plural': '수상 및 학술대회',
                'ordering': ['display_order', '-date'],
            },
        ),
    ]
