# Generated by Django 4.2.23 on 2025-07-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_add_email_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoteitem',
            options={'ordering': ['created_at'], 'verbose_name': '견적 항목 (견적서 내 서비스 항목)', 'verbose_name_plural': '견적 항목 (견적서 내 서비스 항목)'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': '서비스 카테고리 (번역, 통역, 기타 등 카테고리)', 'verbose_name_plural': '서비스 카테고리 (번역, 통역, 기타 등 카테고리)'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': '서비스 유형 (동시 통역, 순차 통역 등 상세 서비스 유형)', 'verbose_name_plural': '서비스 유형 (동시, 순차 등 상세 서비스 유형)'},
        ),
    ]
